install.packages("sp")
install.packages("raster")
install.packages("rgdal")
install.packages("spatialEco")
install.packages('maptools')
install.packages("BiocManager")
BiocManager::install("EBImage")
devtools::install_github("filipematias23/FIELDimageR", dependencies=FALSE)
